service: serverless

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline

custom:
  serverless-offline:
    port: 8080

functions:
  hello:
    handler: graphql/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
